import PptxGenJS from 'pptxgenjs'
import type { LandscapeDTO, Competitor } from '@/types/competitive'

// LandscapeBrief design tokens
const NAVY = '1B2A4A'      // deep navy #1B2A4A
const VERMILLION = 'C1440E' // vermillion #C1440E
const WHITE = 'FFFFFF'
const NEAR_WHITE = 'FAFAF8'
const STEEL = '9BA8B4'     // data neutral
const LIGHT_GREY = 'E2E1DE'
const TEXT = '1B2A4A'
const TEXT_SEC = '6B7280'

const TIER_COLORS: Record<string, string> = {
  direct: 'C1440E',
  indirect: '4A6FA5',
  aspirational: '1B2A4A',
  emerging: '9BA8B4',
}

function positionToFraction(value: number): number {
  // Convert -100..100 to 0..1
  return (value + 100) / 200
}

function truncate(s: string, max: number): string {
  return s.length > max ? s.slice(0, max - 1) + '…' : s
}

export async function generateLandscapePptx(landscape: LandscapeDTO): Promise<Blob> {
  const pptx = new PptxGenJS()
  pptx.layout = 'LAYOUT_16x9'
  pptx.author = 'LandscapeBrief'
  pptx.title = landscape.title

  const competitors = Object.values(landscape.competitors)
  const today = new Date().toLocaleDateString('en-GB', {
    day: 'numeric', month: 'long', year: 'numeric',
  })

  // ────── SLIDE 1: COVER ──────
  const cover = pptx.addSlide()
  cover.background = { color: NEAR_WHITE }

  // Vermillion accent bar (top)
  cover.addShape(pptx.ShapeType.rect, {
    x: 0, y: 0, w: '100%', h: 0.08,
    fill: { color: VERMILLION },
  })

  // Left accent stripe
  cover.addShape(pptx.ShapeType.rect, {
    x: 0, y: 0, w: 0.12, h: '100%',
    fill: { color: NAVY },
  })

  // Title
  cover.addText(landscape.title, {
    x: 0.6, y: 1.4, w: 8.6, h: 1.4,
    fontSize: 40,
    bold: true,
    color: NAVY,
    fontFace: 'Palatino Linotype',
    breakLine: false,
  })

  // Subtitle
  cover.addText('Competitive Landscape Report', {
    x: 0.6, y: 2.9, w: 8, h: 0.5,
    fontSize: 18,
    color: VERMILLION,
    fontFace: 'Helvetica',
    italic: false,
  })

  // Meta line
  cover.addText(`${competitors.length} competitors analysed  |  ${today}`, {
    x: 0.6, y: 3.55, w: 8, h: 0.35,
    fontSize: 12,
    color: STEEL,
    fontFace: 'Helvetica',
  })

  // Axis labels
  cover.addText(`X axis: ${landscape.axisXLabel}  |  Y axis: ${landscape.axisYLabel}`, {
    x: 0.6, y: 4.0, w: 8, h: 0.3,
    fontSize: 11,
    color: TEXT_SEC,
    fontFace: 'Helvetica',
  })

  // Branding footer
  cover.addText('Generated by LandscapeBrief', {
    x: 0.6, y: 4.9, w: 4, h: 0.3,
    fontSize: 9,
    color: STEEL,
    fontFace: 'Helvetica',
  })

  // ────── SLIDE 2: MARKET SUMMARY ──────
  const summary = pptx.addSlide()
  summary.background = { color: WHITE }

  _addSlideHeader(summary, pptx, 'Market Summary', landscape.title)

  // Executive summary block
  summary.addShape(pptx.ShapeType.roundRect, {
    x: 0.4, y: 1.0, w: 9.2, h: 1.6,
    fill: { color: NEAR_WHITE },
    rectRadius: 0.08,
    line: { color: LIGHT_GREY, width: 0.5 },
  })

  summary.addText(landscape.executiveSummary, {
    x: 0.65, y: 1.1, w: 8.7, h: 1.4,
    fontSize: 12,
    color: NAVY,
    fontFace: 'Helvetica',
    valign: 'top',
    wrap: true,
  })

  // Stats bar
  const directCount = competitors.filter(c => c.tier === 'direct').length
  const indirectCount = competitors.filter(c => c.tier === 'indirect').length
  const highConf = competitors.filter(c => c.confidence === 'high').length

  const stats = [
    { label: 'Total competitors', value: String(competitors.length) },
    { label: 'Direct', value: String(directCount) },
    { label: 'Indirect / Other', value: String(indirectCount) },
    { label: 'High confidence', value: String(highConf) },
  ]

  stats.forEach((stat, i) => {
    const x = 0.4 + i * 2.35
    summary.addShape(pptx.ShapeType.roundRect, {
      x, y: 2.85, w: 2.1, h: 1.0,
      fill: { color: i === 0 ? NAVY : NEAR_WHITE },
      rectRadius: 0.07,
      line: { color: LIGHT_GREY, width: 0.5 },
    })
    summary.addText(stat.value, {
      x: x + 0.15, y: 2.92, w: 1.8, h: 0.52,
      fontSize: 28,
      bold: true,
      color: i === 0 ? WHITE : NAVY,
      fontFace: 'Helvetica',
    })
    summary.addText(stat.label, {
      x: x + 0.15, y: 3.46, w: 1.8, h: 0.3,
      fontSize: 9,
      color: i === 0 ? NEAR_WHITE : STEEL,
      fontFace: 'Helvetica',
    })
  })

  // Methodology note
  summary.addText('Methodology: AI-powered analysis of competitor positioning across two key dimensions. Scores normalised to −100 → +100 per axis.', {
    x: 0.4, y: 4.1, w: 9.2, h: 0.5,
    fontSize: 9,
    color: STEEL,
    fontFace: 'Helvetica',
    italic: true,
  })

  // ────── SLIDE 3: COMPETITIVE QUADRANT ──────
  const quadrant = pptx.addSlide()
  quadrant.background = { color: WHITE }

  _addSlideHeader(quadrant, pptx, 'Competitive Quadrant', landscape.title)

  // Chart area boundaries (in inches, slide is 10 x 5.63)
  const chartL = 0.5
  const chartT = 0.9
  const chartR = 7.8
  const chartB = 5.25
  const chartW = chartR - chartL
  const chartH = chartB - chartT
  const midX = chartL + chartW / 2
  const midY = chartT + chartH / 2

  // Quadrant backgrounds
  const qBgs: Array<{ x: number; y: number; w: number; h: number; color: string }> = [
    { x: chartL, y: chartT, w: chartW / 2, h: chartH / 2, color: 'F0EFF5' },          // TL
    { x: midX, y: chartT, w: chartW / 2, h: chartH / 2, color: 'FDF8F6' },            // TR
    { x: chartL, y: midY, w: chartW / 2, h: chartH / 2, color: 'F8F9FA' },            // BL
    { x: midX, y: midY, w: chartW / 2, h: chartH / 2, color: NEAR_WHITE },            // BR
  ]
  qBgs.forEach(q => {
    quadrant.addShape(pptx.ShapeType.rect, {
      x: q.x, y: q.y, w: q.w, h: q.h,
      fill: { color: q.color },
      line: { color: LIGHT_GREY, width: 0.25 },
    })
  })

  // Axis lines
  // Horizontal (X axis)
  quadrant.addShape(pptx.ShapeType.line, {
    x: chartL, y: midY, w: chartW, h: 0,
    line: { color: NAVY, width: 1, dashType: 'solid' },
  })
  // Vertical (Y axis)
  quadrant.addShape(pptx.ShapeType.line, {
    x: midX, y: chartT, w: 0, h: chartH,
    line: { color: NAVY, width: 1, dashType: 'solid' },
  })

  // Axis labels
  quadrant.addText(`← Low ${landscape.axisXLabel}`, {
    x: chartL, y: midY - 0.22, w: chartW / 2, h: 0.18,
    fontSize: 7, color: STEEL, fontFace: 'Helvetica', align: 'left',
  })
  quadrant.addText(`High ${landscape.axisXLabel} →`, {
    x: midX, y: midY - 0.22, w: chartW / 2, h: 0.18,
    fontSize: 7, color: STEEL, fontFace: 'Helvetica', align: 'right',
  })
  quadrant.addText(`High ${landscape.axisYLabel}`, {
    x: midX + 0.05, y: chartT, w: 1.5, h: 0.18,
    fontSize: 7, color: STEEL, fontFace: 'Helvetica',
  })
  quadrant.addText(`Low ${landscape.axisYLabel}`, {
    x: midX + 0.05, y: chartB - 0.2, w: 1.5, h: 0.18,
    fontSize: 7, color: STEEL, fontFace: 'Helvetica',
  })

  // Competitor dots + labels
  competitors.forEach(comp => {
    const dotX = chartL + positionToFraction(comp.axisX) * chartW
    const dotY = chartT + (1 - positionToFraction(comp.axisY)) * chartH
    const dotR = 0.09
    const color = TIER_COLORS[comp.tier] || NAVY

    // Dot
    quadrant.addShape(pptx.ShapeType.ellipse, {
      x: dotX - dotR, y: dotY - dotR, w: dotR * 2, h: dotR * 2,
      fill: { color },
      line: { color: WHITE, width: 1 },
    })

    // Label (offset right of dot, clamp to chart area)
    const labelX = Math.min(dotX + dotR + 0.04, chartR - 1.2)
    quadrant.addText(truncate(comp.name, 16), {
      x: labelX, y: dotY - 0.1, w: 1.3, h: 0.2,
      fontSize: 6.5, color: NAVY, fontFace: 'Helvetica', bold: false,
    })
  })

  // "Your position" marker
  if (landscape.yourPosition) {
    const px = chartL + positionToFraction(landscape.yourPosition.axisX) * chartW
    const py = chartT + (1 - positionToFraction(landscape.yourPosition.axisY)) * chartH
    const r = 0.1
    quadrant.addShape(pptx.ShapeType.ellipse, {
      x: px - r, y: py - r, w: r * 2, h: r * 2,
      fill: { type: 'none' },
      line: { color: NAVY, width: 1.5, dashType: 'dash' },
    })
    quadrant.addText(`${landscape.yourPosition.name} (you)`, {
      x: px + r + 0.04, y: py - 0.1, w: 1.6, h: 0.2,
      fontSize: 6.5, color: NAVY, fontFace: 'Helvetica', bold: true,
    })
  }

  // Legend (right panel)
  const legendX = 8.05
  quadrant.addText('Legend', {
    x: legendX, y: 1.0, w: 1.8, h: 0.25,
    fontSize: 9, bold: true, color: NAVY, fontFace: 'Helvetica',
  })

  const tierLabels = [
    { key: 'direct', label: 'Direct' },
    { key: 'indirect', label: 'Indirect' },
    { key: 'aspirational', label: 'Aspirational' },
    { key: 'emerging', label: 'Emerging' },
  ]
  tierLabels.forEach((t, i) => {
    const ly = 1.3 + i * 0.32
    quadrant.addShape(pptx.ShapeType.ellipse, {
      x: legendX, y: ly, w: 0.14, h: 0.14,
      fill: { color: TIER_COLORS[t.key] || NAVY },
    })
    quadrant.addText(t.label, {
      x: legendX + 0.2, y: ly - 0.01, w: 1.5, h: 0.18,
      fontSize: 8, color: TEXT, fontFace: 'Helvetica',
    })
  })

  // ────── SLIDE 4: COMPETITOR PROFILES ──────
  const profiles = pptx.addSlide()
  profiles.background = { color: WHITE }

  _addSlideHeader(profiles, pptx, 'Competitor Profiles', landscape.title)

  // Table header
  const colW = [2.0, 0.7, 0.7, 2.5, 2.5]
  const headerCells: PptxGenJS.TableCell[] = [
    { text: 'Company', options: { bold: true, fontSize: 9, color: WHITE, fill: { color: NAVY }, fontFace: 'Helvetica' } },
    { text: landscape.axisXLabel, options: { bold: true, fontSize: 8, color: WHITE, fill: { color: NAVY }, fontFace: 'Helvetica', align: 'center' } },
    { text: landscape.axisYLabel, options: { bold: true, fontSize: 8, color: WHITE, fill: { color: NAVY }, fontFace: 'Helvetica', align: 'center' } },
    { text: 'Key Strength', options: { bold: true, fontSize: 9, color: WHITE, fill: { color: NAVY }, fontFace: 'Helvetica' } },
    { text: 'Key Weakness', options: { bold: true, fontSize: 9, color: WHITE, fill: { color: NAVY }, fontFace: 'Helvetica' } },
  ]

  const tableRows: PptxGenJS.TableCell[][] = [headerCells]

  const displayComps = competitors.slice(0, 14) // limit for slide space
  displayComps.forEach((comp, i) => {
    const rowBg = i % 2 === 0 ? NEAR_WHITE : WHITE
    const tierColor = TIER_COLORS[comp.tier] || NAVY

    tableRows.push([
      {
        text: comp.name,
        options: { fontSize: 9, color: NAVY, fill: { color: rowBg }, fontFace: 'Helvetica', bold: true },
      },
      {
        text: String(comp.axisX),
        options: { fontSize: 9, color: tierColor, fill: { color: rowBg }, fontFace: 'Helvetica', align: 'center' },
      },
      {
        text: String(comp.axisY),
        options: { fontSize: 9, color: tierColor, fill: { color: rowBg }, fontFace: 'Helvetica', align: 'center' },
      },
      {
        text: comp.strengths[0] ? truncate(comp.strengths[0], 55) : '—',
        options: { fontSize: 8, color: TEXT, fill: { color: rowBg }, fontFace: 'Helvetica' },
      },
      {
        text: comp.weaknesses[0] ? truncate(comp.weaknesses[0], 55) : '—',
        options: { fontSize: 8, color: TEXT, fill: { color: rowBg }, fontFace: 'Helvetica' },
      },
    ])
  })

  profiles.addTable(tableRows, {
    x: 0.35, y: 0.9, w: 9.3,
    colW,
    border: { type: 'solid', pt: 0.3, color: LIGHT_GREY },
    rowH: 0.3,
  })

  if (competitors.length > 14) {
    profiles.addText(`+ ${competitors.length - 14} more competitors not shown`, {
      x: 0.35, y: 5.2, w: 5, h: 0.25,
      fontSize: 8, italic: true, color: STEEL, fontFace: 'Helvetica',
    })
  }

  // ────── SLIDE 5: STRATEGIC IMPLICATIONS ──────
  const strategic = pptx.addSlide()
  strategic.background = { color: WHITE }

  _addSlideHeader(strategic, pptx, 'Strategic Implications', landscape.title)

  // Executive summary as strategic context
  strategic.addShape(pptx.ShapeType.roundRect, {
    x: 0.35, y: 0.95, w: 9.3, h: 0.9,
    fill: { color: NEAR_WHITE },
    rectRadius: 0.07,
    line: { color: LIGHT_GREY, width: 0.5 },
  })
  strategic.addText('Market Context', {
    x: 0.55, y: 1.0, w: 3, h: 0.25,
    fontSize: 8, bold: true, color: VERMILLION, fontFace: 'Helvetica',
  })
  strategic.addText(truncate(landscape.executiveSummary, 280), {
    x: 0.55, y: 1.25, w: 9.0, h: 0.55,
    fontSize: 9, color: NAVY, fontFace: 'Helvetica', wrap: true,
  })

  // Derive key strategic recommendations from data
  const topDirect = competitors.filter(c => c.tier === 'direct').sort((a, b) => b.axisX - a.axisX)
  const topEmerging = competitors.filter(c => c.tier === 'emerging')
  const highConf2 = competitors.filter(c => c.confidence === 'high').length
  const lowConf = competitors.filter(c => c.confidence === 'low').length

  const implications: string[] = []

  if (topDirect.length > 0) {
    implications.push(`${topDirect.length} direct competitors identified. Leading on ${landscape.axisXLabel}: ${topDirect.slice(0, 2).map(c => c.name).join(', ')}.`)
  }
  if (topEmerging.length > 0) {
    implications.push(`${topEmerging.length} emerging player${topEmerging.length > 1 ? 's' : ''} to monitor: ${topEmerging.slice(0, 3).map(c => c.name).join(', ')}.`)
  }
  if (highConf2 > 0) {
    implications.push(`${highConf2} competitor${highConf2 > 1 ? 's' : ''} analysed with high confidence — strongest signal data for decision-making.`)
  }
  if (lowConf > 0) {
    implications.push(`${lowConf} competitor${lowConf > 1 ? 's' : ''} with limited public data — consider primary research to fill gaps.`)
  }
  if (landscape.whitespaceOpportunities.length > 0) {
    implications.push(`${landscape.whitespaceOpportunities.length} whitespace opportunit${landscape.whitespaceOpportunities.length > 1 ? 'ies' : 'y'} identified — see Opportunity Map slide.`)
  }

  implications.forEach((impl, i) => {
    const y = 2.05 + i * 0.55
    strategic.addShape(pptx.ShapeType.rect, {
      x: 0.35, y: y + 0.06, w: 0.04, h: 0.3,
      fill: { color: VERMILLION },
    })
    strategic.addText(impl, {
      x: 0.55, y, w: 9.1, h: 0.5,
      fontSize: 10, color: NAVY, fontFace: 'Helvetica', wrap: true,
    })
  })

  // ────── SLIDE 6: OPPORTUNITY MAP ──────
  const opps = pptx.addSlide()
  opps.background = { color: WHITE }

  _addSlideHeader(opps, pptx, 'Opportunity Map', landscape.title)

  opps.addText('Strategic gaps identified in the competitive landscape — areas with little or no competition.', {
    x: 0.35, y: 0.88, w: 9.3, h: 0.3,
    fontSize: 9, color: STEEL, fontFace: 'Helvetica', italic: true,
  })

  if (landscape.whitespaceOpportunities.length === 0) {
    opps.addText('No whitespace opportunities were identified in this landscape.', {
      x: 0.35, y: 1.4, w: 9.3, h: 0.4,
      fontSize: 11, color: STEEL, fontFace: 'Helvetica', italic: true,
    })
  } else {
    landscape.whitespaceOpportunities.slice(0, 6).forEach((opp, i) => {
      const col = i % 2
      const row = Math.floor(i / 2)
      const x = 0.35 + col * 4.75
      const y = 1.25 + row * 1.25

      opps.addShape(pptx.ShapeType.roundRect, {
        x, y, w: 4.45, h: 1.1,
        fill: { color: i % 2 === 0 ? NEAR_WHITE : 'F0EFF5' },
        rectRadius: 0.08,
        line: { color: LIGHT_GREY, width: 0.5 },
      })

      // Number badge
      opps.addShape(pptx.ShapeType.ellipse, {
        x: x + 0.12, y: y + 0.12, w: 0.26, h: 0.26,
        fill: { color: VERMILLION },
      })
      opps.addText(String(i + 1).padStart(2, '0'), {
        x: x + 0.12, y: y + 0.12, w: 0.26, h: 0.26,
        fontSize: 8, bold: true, color: WHITE, fontFace: 'Helvetica',
        align: 'center', valign: 'middle',
      })

      opps.addText(truncate(opp, 160), {
        x: x + 0.5, y: y + 0.1, w: 3.8, h: 0.9,
        fontSize: 9, color: NAVY, fontFace: 'Helvetica', wrap: true, valign: 'top',
      })
    })

    if (landscape.whitespaceOpportunities.length > 6) {
      opps.addText(`+ ${landscape.whitespaceOpportunities.length - 6} additional opportunities identified.`, {
        x: 0.35, y: 5.15, w: 5, h: 0.25,
        fontSize: 8, italic: true, color: STEEL, fontFace: 'Helvetica',
      })
    }
  }

  // Footer on all slides — add LandscapeBrief credit
  ;[cover, summary, quadrant, profiles, strategic, opps].forEach(slide => {
    slide.addText('landscapebrief.com', {
      x: 8.5, y: 5.35, w: 1.4, h: 0.2,
      fontSize: 7, color: STEEL, fontFace: 'Helvetica', align: 'right',
    })
  })

  const output = await pptx.write({ outputType: 'blob' }) as Blob
  return output
}

// ── Shared helper ──

function _addSlideHeader(
  slide: PptxGenJS.Slide,
  pptx: PptxGenJS,
  title: string,
  subtitle: string,
) {
  // Thin vermillion rule
  slide.addShape(pptx.ShapeType.rect, {
    x: 0, y: 0, w: '100%', h: 0.06,
    fill: { color: VERMILLION },
  })

  // Section title
  slide.addText(title, {
    x: 0.35, y: 0.12, w: 7, h: 0.45,
    fontSize: 20,
    bold: true,
    color: NAVY,
    fontFace: 'Palatino Linotype',
  })

  // Landscape name (right)
  slide.addText(subtitle, {
    x: 7.0, y: 0.18, w: 2.85, h: 0.3,
    fontSize: 8,
    color: STEEL,
    fontFace: 'Helvetica',
    align: 'right',
  })

  // Divider
  slide.addShape(pptx.ShapeType.line, {
    x: 0.35, y: 0.65, w: 9.3, h: 0,
    line: { color: LIGHT_GREY, width: 0.5 },
  })
}
