import { jsPDF } from 'jspdf'
import type { LandscapeDTO, Competitor } from '@/types/competitive'

// LandscapeBrief design tokens
const NAVY = { r: 27, g: 42, b: 74 }      // #1B2A4A
const VERMILLION = { r: 193, g: 68, b: 14 } // #C1440E
const WHITE = { r: 255, g: 255, b: 255 }
const NEAR_WHITE = { r: 250, g: 250, b: 248 } // #FAFAF8
const STEEL = { r: 155, g: 168, b: 180 }   // #9BA8B4
const LIGHT_GREY = { r: 226, g: 225, b: 222 } // #E2E1DE
const TEXT = { r: 27, g: 42, b: 74 }
const TEXT_SEC = { r: 107, g: 114, b: 128 }

type RGB = { r: number; g: number; b: number }

function sf(doc: jsPDF, c: RGB) { doc.setFillColor(c.r, c.g, c.b) }
function st(doc: jsPDF, c: RGB) { doc.setTextColor(c.r, c.g, c.b) }
function sd(doc: jsPDF, c: RGB) { doc.setDrawColor(c.r, c.g, c.b) }

const TIER_COLORS: Record<string, RGB> = {
  direct: VERMILLION,
  indirect: { r: 74, g: 111, b: 165 },    // slate blue
  aspirational: NAVY,
  emerging: STEEL,
}

function positionToFraction(value: number): number {
  return (value + 100) / 200
}

function truncate(s: string, max: number): string {
  return s.length > max ? s.slice(0, max - 1) + '\u2026' : s
}

function addPageHeader(doc: jsPDF, title: string, subtitle: string, W: number) {
  // Thin vermillion rule
  sf(doc, VERMILLION)
  doc.rect(0, 0, W, 2, 'F')

  // Section title
  st(doc, NAVY)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(18)
  doc.text(title, 15, 12)

  // Subtitle right-aligned
  st(doc, STEEL)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.text(subtitle, W - 15, 11, { align: 'right' })

  // Divider
  sd(doc, LIGHT_GREY)
  doc.setLineWidth(0.3)
  doc.line(15, 16, W - 15, 16)
}

function addFooter(doc: jsPDF, pageNum: number, W: number, H: number) {
  sf(doc, NEAR_WHITE)
  doc.rect(0, H - 8, W, 8, 'F')
  sd(doc, LIGHT_GREY)
  doc.setLineWidth(0.2)
  doc.line(0, H - 8, W, H - 8)
  st(doc, STEEL)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7)
  doc.text('landscapebrief.com', 15, H - 3)
  doc.text(`Page ${pageNum}`, W - 15, H - 3, { align: 'right' })
}

export async function generateLandscapePdf(landscape: LandscapeDTO): Promise<Blob> {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' })
  const W = 297
  const H = 210

  const competitors = Object.values(landscape.competitors)
  const today = new Date().toLocaleDateString('en-GB', {
    day: 'numeric', month: 'long', year: 'numeric',
  })

  let pageNum = 1

  // ────── PAGE 1: COVER ──────
  sf(doc, NEAR_WHITE)
  doc.rect(0, 0, W, H, 'F')

  // Navy left stripe
  sf(doc, NAVY)
  doc.rect(0, 0, 8, H, 'F')

  // Vermillion accent bar at top
  sf(doc, VERMILLION)
  doc.rect(0, 0, W, 3, 'F')

  // Title
  st(doc, NAVY)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(32)
  const titleLines = doc.splitTextToSize(landscape.title, W - 60)
  doc.text(titleLines, 25, 55)

  // Subtitle
  st(doc, VERMILLION)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(16)
  doc.text('Competitive Landscape Report', 25, 78)

  // Meta
  st(doc, TEXT_SEC)
  doc.setFontSize(11)
  doc.text(`${competitors.length} competitors analysed  |  ${today}`, 25, 90)
  doc.setFontSize(10)
  doc.text(`X axis: ${landscape.axisXLabel}  |  Y axis: ${landscape.axisYLabel}`, 25, 99)

  // Footer branding
  st(doc, STEEL)
  doc.setFontSize(9)
  doc.text('Generated by LandscapeBrief', 25, H - 18)

  addFooter(doc, pageNum, W, H)
  pageNum++

  // ────── PAGE 2: EXECUTIVE SUMMARY ──────
  doc.addPage('a4', 'landscape')
  sf(doc, WHITE)
  doc.rect(0, 0, W, H, 'F')

  addPageHeader(doc, 'Market Summary', landscape.title, W)

  let y = 24

  // Summary block
  sf(doc, NEAR_WHITE)
  doc.roundedRect(15, y, W - 30, 28, 2, 2, 'F')
  sd(doc, LIGHT_GREY)
  doc.roundedRect(15, y, W - 30, 28, 2, 2, 'S')

  st(doc, NAVY)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  const summaryLines = doc.splitTextToSize(landscape.executiveSummary, W - 44)
  doc.text(summaryLines.slice(0, 5), 22, y + 8)
  y += 34

  // Stats row
  const directCount = competitors.filter(c => c.tier === 'direct').length
  const indirectCount = competitors.filter(c => c.tier === 'indirect').length
  const highConf = competitors.filter(c => c.confidence === 'high').length

  const stats = [
    { label: 'Total competitors', value: String(competitors.length) },
    { label: 'Direct', value: String(directCount) },
    { label: 'Indirect / Other', value: String(indirectCount) },
    { label: 'High confidence', value: String(highConf) },
  ]

  const statW = 60
  stats.forEach((stat, i) => {
    const x = 15 + i * (statW + 3)
    sf(doc, i === 0 ? NAVY : NEAR_WHITE)
    doc.roundedRect(x, y, statW, 22, 2, 2, 'F')
    sd(doc, LIGHT_GREY)
    doc.roundedRect(x, y, statW, 22, 2, 2, 'S')

    st(doc, i === 0 ? WHITE : NAVY)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(18)
    doc.text(stat.value, x + 5, y + 13)

    st(doc, i === 0 ? { r: 200, g: 210, b: 220 } : STEEL)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.text(stat.label, x + 5, y + 20)
  })

  y += 28

  // Methodology
  st(doc, STEEL)
  doc.setFont('helvetica', 'italic')
  doc.setFontSize(8)
  doc.text('Methodology: AI-powered analysis of competitor positioning across two key dimensions. Scores normalised to −100 → +100 per axis.', 15, y + 4)

  addFooter(doc, pageNum, W, H)
  pageNum++

  // ────── PAGE 3: COMPETITIVE QUADRANT ──────
  doc.addPage('a4', 'landscape')
  sf(doc, WHITE)
  doc.rect(0, 0, W, H, 'F')

  addPageHeader(doc, 'Competitive Quadrant', landscape.title, W)

  // Chart area
  const MARGIN = 15
  const CHART_TOP = 22
  const CHART_BOTTOM = H - 20
  const CHART_LEFT = MARGIN + 10
  const CHART_RIGHT = W - 60  // leave room for legend
  const CW = CHART_RIGHT - CHART_LEFT
  const CH = CHART_BOTTOM - CHART_TOP
  const MX = CHART_LEFT + CW / 2
  const MY = CHART_TOP + CH / 2

  // Quadrant backgrounds
  const qBgs = [
    { x: CHART_LEFT, y: CHART_TOP, w: CW / 2, h: CH / 2, r: 240, g: 239, b: 245 },
    { x: MX, y: CHART_TOP, w: CW / 2, h: CH / 2, r: 253, g: 248, b: 246 },
    { x: CHART_LEFT, y: MY, w: CW / 2, h: CH / 2, r: 248, g: 249, b: 250 },
    { x: MX, y: MY, w: CW / 2, h: CH / 2, r: 250, g: 250, b: 248 },
  ]
  qBgs.forEach(q => {
    doc.setFillColor(q.r, q.g, q.b)
    doc.rect(q.x, q.y, q.w, q.h, 'F')
  })

  // Border
  sd(doc, LIGHT_GREY)
  doc.setLineWidth(0.3)
  doc.rect(CHART_LEFT, CHART_TOP, CW, CH, 'S')

  // Axis lines
  sd(doc, { r: 27, g: 42, b: 74 })
  doc.setLineWidth(0.5)
  doc.setGState(new (doc as unknown as { GState: new (opts: { opacity: number }) => unknown }).GState({ opacity: 0.3 }))
  doc.line(CHART_LEFT, MY, CHART_RIGHT, MY)  // X axis
  doc.line(MX, CHART_TOP, MX, CHART_BOTTOM)  // Y axis
  doc.setGState(new (doc as unknown as { GState: new (opts: { opacity: number }) => unknown }).GState({ opacity: 1 }))

  // Axis labels
  st(doc, STEEL)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7)
  doc.text(`← Low ${landscape.axisXLabel}`, CHART_LEFT + 2, MY - 2)
  doc.text(`High ${landscape.axisXLabel} →`, CHART_RIGHT - 2, MY - 2, { align: 'right' })
  doc.text(`High ${landscape.axisYLabel}`, MX + 2, CHART_TOP + 5)
  doc.text(`Low ${landscape.axisYLabel}`, MX + 2, CHART_BOTTOM - 3)

  // Competitor dots
  competitors.forEach(comp => {
    const cx = CHART_LEFT + positionToFraction(comp.axisX) * CW
    const cy = CHART_TOP + (1 - positionToFraction(comp.axisY)) * CH
    const color = TIER_COLORS[comp.tier] || NAVY
    const r = 2.5

    sf(doc, color)
    sd(doc, WHITE)
    doc.setLineWidth(0.5)
    doc.circle(cx, cy, r, 'FD')

    // Label
    st(doc, NAVY)
    doc.setFontSize(5.5)
    const label = truncate(comp.name, 16)
    doc.text(label, Math.min(cx + r + 1.5, CHART_RIGHT - 18), cy + 1.5)
  })

  // "Your position" marker
  if (landscape.yourPosition) {
    const px = CHART_LEFT + positionToFraction(landscape.yourPosition.axisX) * CW
    const py = CHART_TOP + (1 - positionToFraction(landscape.yourPosition.axisY)) * CH
    const r = 3.5
    sf(doc, NAVY)
    sd(doc, NAVY)
    doc.setLineWidth(0.8)
    doc.setLineDashPattern([1.5, 1], 0)
    doc.circle(px, py, r, 'S')
    doc.setLineDashPattern([], 0)
    sf(doc, NAVY)
    doc.circle(px, py, 1.5, 'F')
    st(doc, NAVY)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(5.5)
    doc.text(`${landscape.yourPosition.name} (you)`, px + r + 1.5, py + 1.5)
  }

  // Legend (right side)
  const legendX = CHART_RIGHT + 5
  st(doc, NAVY)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8)
  doc.text('Legend', legendX, CHART_TOP + 8)

  const tierLabels = [
    { key: 'direct', label: 'Direct' },
    { key: 'indirect', label: 'Indirect' },
    { key: 'aspirational', label: 'Aspirational' },
    { key: 'emerging', label: 'Emerging' },
  ]
  tierLabels.forEach((t, i) => {
    const ly = CHART_TOP + 16 + i * 9
    const color = TIER_COLORS[t.key] || NAVY
    sf(doc, color)
    doc.circle(legendX + 2, ly, 2, 'F')
    st(doc, TEXT)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(7.5)
    doc.text(t.label, legendX + 6, ly + 1)
  })

  addFooter(doc, pageNum, W, H)
  pageNum++

  // ────── PAGE 4: COMPETITOR PROFILES (table) ──────
  doc.addPage('a4', 'landscape')
  sf(doc, WHITE)
  doc.rect(0, 0, W, H, 'F')

  addPageHeader(doc, 'Competitor Profiles', landscape.title, W)

  y = 22

  // Table header
  const cols = [
    { x: 15, w: 48, label: 'Company' },
    { x: 63, w: 20, label: landscape.axisXLabel.slice(0, 10) },
    { x: 83, w: 20, label: landscape.axisYLabel.slice(0, 10) },
    { x: 103, w: 80, label: 'Key Strength' },
    { x: 183, w: 99, label: 'Key Weakness' },
  ]

  sf(doc, NAVY)
  doc.rect(15, y, W - 30, 8, 'F')
  st(doc, WHITE)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8)
  cols.forEach(col => doc.text(col.label, col.x + 2, y + 5.5))
  y += 8

  const displayComps = competitors.slice(0, 18)
  displayComps.forEach((comp, i) => {
    if (y > H - 15) return // skip overflow for now

    sf(doc, i % 2 === 0 ? NEAR_WHITE : WHITE)
    doc.rect(15, y, W - 30, 7, 'F')

    const tierColor = TIER_COLORS[comp.tier] || NAVY
    st(doc, NAVY)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(8)
    doc.text(truncate(comp.name, 22), cols[0].x + 2, y + 5)

    st(doc, tierColor)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.text(String(comp.axisX), cols[1].x + 2, y + 5)
    doc.text(String(comp.axisY), cols[2].x + 2, y + 5)

    st(doc, TEXT)
    doc.text(truncate(comp.strengths[0] || '—', 38), cols[3].x + 2, y + 5)
    doc.text(truncate(comp.weaknesses[0] || '—', 46), cols[4].x + 2, y + 5)

    y += 7
  })

  if (competitors.length > 18) {
    st(doc, STEEL)
    doc.setFont('helvetica', 'italic')
    doc.setFontSize(8)
    doc.text(`+ ${competitors.length - 18} more competitors not shown`, 15, y + 5)
  }

  addFooter(doc, pageNum, W, H)
  pageNum++

  // ────── PAGE 5: STRATEGIC IMPLICATIONS ──────
  doc.addPage('a4', 'landscape')
  sf(doc, WHITE)
  doc.rect(0, 0, W, H, 'F')

  addPageHeader(doc, 'Strategic Implications', landscape.title, W)

  y = 24

  // Summary context box
  sf(doc, NEAR_WHITE)
  doc.roundedRect(15, y, W - 30, 22, 2, 2, 'F')
  sd(doc, LIGHT_GREY)
  doc.roundedRect(15, y, W - 30, 22, 2, 2, 'S')

  st(doc, VERMILLION)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8)
  doc.text('Market Context', 20, y + 6)
  st(doc, NAVY)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  const ctxLines = doc.splitTextToSize(landscape.executiveSummary, W - 44)
  doc.text(ctxLines.slice(0, 3), 20, y + 12)
  y += 28

  // Implications
  const directCount2 = competitors.filter(c => c.tier === 'direct').length
  const topDirect = competitors.filter(c => c.tier === 'direct').sort((a, b) => b.axisX - a.axisX)
  const topEmerging = competitors.filter(c => c.tier === 'emerging')
  const highConf2 = competitors.filter(c => c.confidence === 'high').length
  const lowConf = competitors.filter(c => c.confidence === 'low').length

  const implications: string[] = []
  if (topDirect.length > 0) {
    implications.push(`${topDirect.length} direct competitors identified. Leading on ${landscape.axisXLabel}: ${topDirect.slice(0, 2).map(c => c.name).join(', ')}.`)
  }
  if (topEmerging.length > 0) {
    implications.push(`${topEmerging.length} emerging player${topEmerging.length > 1 ? 's' : ''} to monitor: ${topEmerging.slice(0, 3).map(c => c.name).join(', ')}.`)
  }
  if (highConf2 > 0) {
    implications.push(`${highConf2} competitor${highConf2 > 1 ? 's' : ''} analysed with high confidence — strongest signal data for decision-making.`)
  }
  if (lowConf > 0) {
    implications.push(`${lowConf} competitor${lowConf > 1 ? 's' : ''} with limited public data — consider primary research to fill gaps.`)
  }
  if (landscape.whitespaceOpportunities.length > 0) {
    implications.push(`${landscape.whitespaceOpportunities.length} whitespace opportunit${landscape.whitespaceOpportunities.length > 1 ? 'ies' : 'y'} identified — see Opportunity Map page.`)
  }

  implications.forEach(impl => {
    // Accent bar
    sf(doc, VERMILLION)
    doc.rect(15, y + 2, 2, 7, 'F')

    st(doc, NAVY)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9.5)
    const lines = doc.splitTextToSize(impl, W - 36)
    doc.text(lines, 21, y + 7)
    y += Math.max(12, lines.length * 5 + 6)
  })

  addFooter(doc, pageNum, W, H)
  pageNum++

  // ────── PAGE 6: OPPORTUNITY MAP ──────
  doc.addPage('a4', 'landscape')
  sf(doc, WHITE)
  doc.rect(0, 0, W, H, 'F')

  addPageHeader(doc, 'Opportunity Map', landscape.title, W)

  y = 24

  st(doc, STEEL)
  doc.setFont('helvetica', 'italic')
  doc.setFontSize(8.5)
  doc.text('Strategic gaps identified in the competitive landscape — areas with little or no competition.', 15, y)
  y += 8

  if (landscape.whitespaceOpportunities.length === 0) {
    st(doc, STEEL)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(11)
    doc.text('No whitespace opportunities were identified in this landscape.', 15, y + 10)
  } else {
    const opps = landscape.whitespaceOpportunities.slice(0, 6)
    const colW2 = (W - 35) / 2
    opps.forEach((opp, i) => {
      const col = i % 2
      const row = Math.floor(i / 2)
      const ox = 15 + col * (colW2 + 5)
      const oy = y + row * 40

      sf(doc, i % 2 === 0 ? NEAR_WHITE : { r: 240, g: 239, b: 245 })
      doc.roundedRect(ox, oy, colW2, 35, 2, 2, 'F')
      sd(doc, LIGHT_GREY)
      doc.roundedRect(ox, oy, colW2, 35, 2, 2, 'S')

      // Number badge
      sf(doc, VERMILLION)
      doc.circle(ox + 7, oy + 7, 4.5, 'F')
      st(doc, WHITE)
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(7)
      doc.text(String(i + 1).padStart(2, '0'), ox + 7, oy + 9, { align: 'center' })

      st(doc, NAVY)
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(8)
      const oppLines = doc.splitTextToSize(opp, colW2 - 22)
      doc.text(oppLines.slice(0, 4), ox + 15, oy + 7)
    })

    if (landscape.whitespaceOpportunities.length > 6) {
      st(doc, STEEL)
      doc.setFont('helvetica', 'italic')
      doc.setFontSize(8)
      doc.text(`+ ${landscape.whitespaceOpportunities.length - 6} additional opportunities identified.`, 15, H - 28)
    }
  }

  addFooter(doc, pageNum, W, H)

  return doc.output('blob')
}
