import { jsPDF } from 'jspdf'
import type { OrganizationDTO, TemplateTokens, Person } from '@/types'

interface PdfOptions {
  organization: OrganizationDTO
  template: TemplateTokens
  chartImageDataUrl: string
  clientName: string
  includeConfidence: boolean
}

const SENIORITY_ORDER: Record<string, number> = {
  'board': 0, 'c-suite': 1, 'evp': 2, 'svp': 3, 'vp': 4,
  'sr-director': 5, 'director': 6, 'sr-manager': 7, 'manager': 8,
  'lead': 9, 'senior-ic': 10, 'ic': 11, 'unknown': 12,
}

function hexToRgb(hex: string): [number, number, number] {
  hex = hex.replace('#', '')
  return [
    parseInt(hex.slice(0, 2), 16),
    parseInt(hex.slice(2, 4), 16),
    parseInt(hex.slice(4, 6), 16),
  ]
}

function sortBySeniority(people: Person[]): Person[] {
  return [...people].sort((a, b) => {
    const diff = (SENIORITY_ORDER[a.seniorityLevel] ?? 12) - (SENIORITY_ORDER[b.seniorityLevel] ?? 12)
    if (diff !== 0) return diff
    return a.name.localeCompare(b.name)
  })
}

export async function generatePdf(opts: PdfOptions): Promise<Blob> {
  const { organization: org, template: t, chartImageDataUrl, clientName, includeConfidence } = opts
  const people = Object.values(org.people)
  const departments = Object.values(org.departments)
  const today = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })

  // A4 landscape
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' })
  const W = 297
  const H = 210

  const isDark = isColorDark(t.colors.background)
  const bg = hexToRgb(t.colors.background)
  const textColor = hexToRgb(t.colors.text)
  const secondaryColor = hexToRgb(t.colors.textSecondary)
  const accentColor = hexToRgb(t.colors.accent)
  const surfaceColor = hexToRgb(t.colors.surface)

  // ────── PAGE 1: COVER ──────
  doc.setFillColor(...bg)
  doc.rect(0, 0, W, H, 'F')

  // Accent bar
  doc.setFillColor(...accentColor)
  doc.rect(0, 0, 6, H, 'F')

  // Client name
  doc.setTextColor(...textColor)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(36)
  doc.text(clientName || 'Organization Chart', 30, 70)

  // Subtitle
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(16)
  doc.setTextColor(...secondaryColor)
  doc.text('Organization Chart Report', 30, 85)

  // Date & stats
  doc.setFontSize(12)
  doc.text(today, 30, 105)
  doc.text(`${people.length} people  |  ${departments.length} departments  |  ${org.completenessScore}% complete`, 30, 115)

  // CompBrief branding
  doc.setFontSize(10)
  doc.setTextColor(...accentColor)
  doc.text('Generated by CompBrief', 30, H - 20)
  doc.setTextColor(...secondaryColor)
  doc.setFontSize(8)
  doc.text('landscapebrief.com', 30, H - 14)

  // ────── PAGE 2: CHART ──────
  doc.addPage('a4', 'landscape')
  doc.setFillColor(...bg)
  doc.rect(0, 0, W, H, 'F')

  // Page header
  doc.setFontSize(10)
  doc.setTextColor(...secondaryColor)
  doc.text(clientName || 'Organization Chart', 15, 12)
  doc.setFont('helvetica', 'normal')
  doc.text(today, W - 15, 12, { align: 'right' })

  // Embed chart image — fit within margins
  const margin = 15
  const imgW = W - margin * 2
  const imgH = H - margin * 2 - 10 // leave space for header

  try {
    doc.addImage(chartImageDataUrl, 'PNG', margin, 20, imgW, imgH)
  } catch {
    // Fallback if image fails
    doc.setTextColor(...textColor)
    doc.setFontSize(14)
    doc.text('Chart image could not be embedded', W / 2, H / 2, { align: 'center' })
  }

  // ────── PAGE 3: STATS ──────
  doc.addPage('a4', 'landscape')
  doc.setFillColor(...bg)
  doc.rect(0, 0, W, H, 'F')

  // Header
  doc.setTextColor(...textColor)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(20)
  doc.text('Organization Summary', 20, 25)

  let y = 40

  // Key metrics row
  const metrics = [
    { label: 'Total People', value: String(org.inferenceStats.totalPeople) },
    { label: 'Departments', value: String(departments.length) },
    { label: 'Completeness', value: `${org.completenessScore}%` },
    { label: 'Orphan Nodes', value: String(org.inferenceStats.orphanNodes) },
  ]

  const metricW = 60
  doc.setFontSize(10)
  metrics.forEach((m, i) => {
    const x = 20 + i * metricW
    doc.setFillColor(...surfaceColor)
    doc.roundedRect(x, y, metricW - 5, 28, 3, 3, 'F')
    doc.setTextColor(...secondaryColor)
    doc.setFont('helvetica', 'normal')
    doc.text(m.label, x + 6, y + 10)
    doc.setTextColor(...textColor)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(18)
    doc.text(m.value, x + 6, y + 22)
    doc.setFontSize(10)
  })

  y += 40

  // Department breakdown
  doc.setTextColor(...textColor)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(14)
  doc.text('Department Breakdown', 20, y)
  y += 8

  // Table header
  doc.setFillColor(...accentColor)
  doc.rect(20, y, W - 40, 8, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(9)
  doc.text('Department', 24, y + 5.5)
  doc.text('Head', 100, y + 5.5)
  doc.text('Members', 180, y + 5.5)
  if (includeConfidence) doc.text('Confidence', 210, y + 5.5)
  y += 8

  const sortedDepts = [...departments].sort((a, b) => b.memberIds.length - a.memberIds.length)

  sortedDepts.forEach((dept, i) => {
    if (y > H - 20) {
      doc.addPage('a4', 'landscape')
      doc.setFillColor(...bg)
      doc.rect(0, 0, W, H, 'F')
      y = 20
    }

    const rowBg = i % 2 === 0 ? surfaceColor : bg
    doc.setFillColor(...rowBg)
    doc.rect(20, y, W - 40, 7, 'F')

    doc.setTextColor(...textColor)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)
    doc.text(dept.name, 24, y + 5)

    const head = dept.headId ? org.people[dept.headId] : null
    doc.text(head?.name || '—', 100, y + 5)
    doc.text(String(dept.memberIds.length), 180, y + 5)

    if (includeConfidence) {
      const [cr, cg, cb] = dept.confidence === 'high' ? [5, 150, 105]
        : dept.confidence === 'medium' ? [217, 119, 6]
        : [220, 38, 38]
      doc.setTextColor(cr, cg, cb)
      doc.text(dept.confidence, 210, y + 5)
    }

    y += 7
  })

  // Confidence summary
  if (includeConfidence) {
    y += 10
    if (y > H - 40) {
      doc.addPage('a4', 'landscape')
      doc.setFillColor(...bg)
      doc.rect(0, 0, W, H, 'F')
      y = 20
    }

    doc.setTextColor(...textColor)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(14)
    doc.text('Confidence Summary', 20, y)
    y += 8

    const confCounts = { high: 0, medium: 0, low: 0 }
    people.forEach(p => { confCounts[p.reportsToConfidence]++ })

    const confItems: { label: string; count: number; color: [number, number, number] }[] = [
      { label: 'High confidence', count: confCounts.high, color: [5, 150, 105] },
      { label: 'Medium confidence', count: confCounts.medium, color: [217, 119, 6] },
      { label: 'Low confidence', count: confCounts.low, color: [220, 38, 38] },
    ]

    confItems.forEach(item => {
      doc.setFillColor(...item.color)
      doc.circle(26, y + 2, 2, 'F')
      doc.setTextColor(...textColor)
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(10)
      doc.text(`${item.label}: ${item.count} (${Math.round(item.count / people.length * 100)}%)`, 32, y + 4)
      y += 8
    })
  }

  // ────── PAGE 4: PEOPLE TABLE ──────
  doc.addPage('a4', 'landscape')
  doc.setFillColor(...bg)
  doc.rect(0, 0, W, H, 'F')

  doc.setTextColor(...textColor)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(20)
  doc.text('People Directory', 20, 25)

  y = 35

  // Table header
  doc.setFillColor(...accentColor)
  doc.rect(15, y, W - 30, 8, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8)
  doc.text('Name', 18, y + 5.5)
  doc.text('Title', 70, y + 5.5)
  doc.text('Department', 155, y + 5.5)
  doc.text('Reports To', 210, y + 5.5)
  if (includeConfidence) doc.text('Confidence', 260, y + 5.5)
  y += 8

  const sorted = sortBySeniority(people)

  sorted.forEach((person, i) => {
    if (y > H - 15) {
      doc.addPage('a4', 'landscape')
      doc.setFillColor(...bg)
      doc.rect(0, 0, W, H, 'F')
      y = 15

      // Repeat header
      doc.setFillColor(...accentColor)
      doc.rect(15, y, W - 30, 8, 'F')
      doc.setTextColor(255, 255, 255)
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(8)
      doc.text('Name', 18, y + 5.5)
      doc.text('Title', 70, y + 5.5)
      doc.text('Department', 155, y + 5.5)
      doc.text('Reports To', 210, y + 5.5)
      if (includeConfidence) doc.text('Confidence', 260, y + 5.5)
      y += 8
    }

    const rowBg = i % 2 === 0 ? surfaceColor : bg
    doc.setFillColor(...rowBg)
    doc.rect(15, y, W - 30, 6.5, 'F')

    doc.setTextColor(...textColor)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)

    doc.text(truncate(person.name, 30), 18, y + 4.5)
    doc.text(truncate(person.normalizedTitle || person.rawTitle, 45), 70, y + 4.5)
    doc.text(truncate(person.department || '—', 28), 155, y + 4.5)

    const manager = person.reportsTo ? org.people[person.reportsTo] : null
    doc.text(truncate(manager?.name || '—', 25), 210, y + 4.5)

    if (includeConfidence) {
      const [cr, cg, cb] = person.reportsToConfidence === 'high' ? [5, 150, 105]
        : person.reportsToConfidence === 'medium' ? [217, 119, 6]
        : [220, 38, 38]
      doc.setTextColor(cr, cg, cb)
      doc.text(person.reportsToConfidence, 260, y + 4.5)
    }

    y += 6.5
  })

  return doc.output('blob')
}

function truncate(s: string, max: number): string {
  return s.length > max ? s.slice(0, max - 1) + '…' : s
}

function isColorDark(hex: string): boolean {
  const [r, g, b] = hexToRgb(hex)
  return (r * 299 + g * 587 + b * 114) / 1000 < 128
}
