import PptxGenJS from 'pptxgenjs'
import type { OrganizationDTO, TemplateTokens } from '@/types'

interface PptxOptions {
  organization: OrganizationDTO
  template: TemplateTokens
  chartImageDataUrl: string
  clientName: string
  includeConfidence: boolean
}

function hexToRgb(hex: string): string {
  // pptxgenjs wants hex without #
  return hex.replace('#', '')
}

function isColorDark(hex: string): boolean {
  hex = hex.replace('#', '')
  const r = parseInt(hex.slice(0, 2), 16)
  const g = parseInt(hex.slice(2, 4), 16)
  const b = parseInt(hex.slice(4, 6), 16)
  return (r * 299 + g * 587 + b * 114) / 1000 < 128
}

export async function generatePptx(opts: PptxOptions): Promise<Blob> {
  const { organization: org, template: t, chartImageDataUrl, clientName, includeConfidence } = opts
  const people = Object.values(org.people)
  const departments = Object.values(org.departments)
  const today = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })

  const pptx = new PptxGenJS()
  pptx.layout = 'LAYOUT_16x9'
  pptx.author = 'CompBrief'
  pptx.title = `${clientName || 'Organization'} — Org Chart`

  const bgColor = hexToRgb(t.colors.background)
  const textColor = hexToRgb(t.colors.text)
  const secondaryColor = hexToRgb(t.colors.textSecondary)
  const accentColor = hexToRgb(t.colors.accent)
  const surfaceColor = hexToRgb(t.colors.surface)

  // ────── SLIDE 1: TITLE ──────
  const slide1 = pptx.addSlide()
  slide1.background = { color: bgColor }

  // Accent bar left
  slide1.addShape(pptx.ShapeType.rect, {
    x: 0, y: 0, w: 0.15, h: '100%',
    fill: { color: accentColor },
  })

  // Client name
  slide1.addText(clientName || 'Organization Chart', {
    x: 0.8, y: 1.8, w: 8, h: 1,
    fontSize: 36,
    bold: true,
    color: textColor,
    fontFace: 'Helvetica',
  })

  // Subtitle
  slide1.addText('Organization Chart Report', {
    x: 0.8, y: 2.8, w: 8, h: 0.5,
    fontSize: 18,
    color: secondaryColor,
    fontFace: 'Helvetica',
  })

  // Date
  slide1.addText(today, {
    x: 0.8, y: 3.5, w: 4, h: 0.4,
    fontSize: 12,
    color: secondaryColor,
    fontFace: 'Helvetica',
  })

  // Stats line
  slide1.addText(
    `${people.length} people  |  ${departments.length} departments  |  ${org.completenessScore}% complete`,
    {
      x: 0.8, y: 3.9, w: 6, h: 0.4,
      fontSize: 12,
      color: secondaryColor,
      fontFace: 'Helvetica',
    }
  )

  // Branding
  slide1.addText('Generated by CompBrief', {
    x: 0.8, y: 4.8, w: 4, h: 0.3,
    fontSize: 10,
    color: accentColor,
    fontFace: 'Helvetica',
  })

  // ────── SLIDE 2: CHART ──────
  const slide2 = pptx.addSlide()
  slide2.background = { color: bgColor }

  // Header
  slide2.addText(clientName || 'Organization Chart', {
    x: 0.3, y: 0.15, w: 4, h: 0.3,
    fontSize: 9,
    color: secondaryColor,
    fontFace: 'Helvetica',
  })
  slide2.addText(today, {
    x: 6, y: 0.15, w: 3.7, h: 0.3,
    fontSize: 9,
    color: secondaryColor,
    fontFace: 'Helvetica',
    align: 'right',
  })

  // Chart image — full-bleed with small margins
  slide2.addImage({
    data: chartImageDataUrl,
    x: 0.3, y: 0.5, w: 9.4, h: 4.8,
    sizing: { type: 'contain', w: 9.4, h: 4.8 },
  })

  // ────── SLIDES 3+: DEPARTMENTS ──────
  const sortedDepts = [...departments].sort((a, b) => b.memberIds.length - a.memberIds.length)

  sortedDepts.forEach(dept => {
    const slide = pptx.addSlide()
    slide.background = { color: bgColor }

    // Accent bar
    slide.addShape(pptx.ShapeType.rect, {
      x: 0, y: 0, w: 0.08, h: '100%',
      fill: { color: dept.color ? hexToRgb(dept.color) : accentColor },
    })

    // Department name
    slide.addText(dept.name, {
      x: 0.5, y: 0.3, w: 9, h: 0.6,
      fontSize: 24,
      bold: true,
      color: textColor,
      fontFace: 'Helvetica',
    })

    // Head info
    const head = dept.headId ? org.people[dept.headId] : null
    slide.addText(`Head: ${head?.name || 'Not identified'}  |  ${dept.memberIds.length} members`, {
      x: 0.5, y: 0.9, w: 9, h: 0.4,
      fontSize: 12,
      color: secondaryColor,
      fontFace: 'Helvetica',
    })

    // Members table
    const memberPeople = dept.memberIds
      .map(id => org.people[id])
      .filter(Boolean)
      .sort((a, b) => (a.seniorityScore ?? 0) - (b.seniorityScore ?? 0))
      .reverse()

    const headerRow: PptxGenJS.TableCell[] = [
      { text: 'Name', options: { bold: true, fontSize: 9, color: 'FFFFFF', fill: { color: accentColor }, fontFace: 'Helvetica' } },
      { text: 'Title', options: { bold: true, fontSize: 9, color: 'FFFFFF', fill: { color: accentColor }, fontFace: 'Helvetica' } },
      { text: 'Reports To', options: { bold: true, fontSize: 9, color: 'FFFFFF', fill: { color: accentColor }, fontFace: 'Helvetica' } },
    ]

    if (includeConfidence) {
      headerRow.push({
        text: 'Confidence',
        options: { bold: true, fontSize: 9, color: 'FFFFFF', fill: { color: accentColor }, fontFace: 'Helvetica' },
      })
    }

    const rows: PptxGenJS.TableCell[][] = [headerRow]

    // Limit to ~12 rows per slide for readability
    const visibleMembers = memberPeople.slice(0, 12)

    visibleMembers.forEach((person, i) => {
      const bgFill = i % 2 === 0 ? surfaceColor : bgColor
      const manager = person.reportsTo ? org.people[person.reportsTo] : null
      const row: PptxGenJS.TableCell[] = [
        { text: person.name, options: { fontSize: 9, color: textColor, fill: { color: bgFill }, fontFace: 'Helvetica' } },
        { text: person.normalizedTitle || person.rawTitle, options: { fontSize: 9, color: textColor, fill: { color: bgFill }, fontFace: 'Helvetica' } },
        { text: manager?.name || '—', options: { fontSize: 9, color: textColor, fill: { color: bgFill }, fontFace: 'Helvetica' } },
      ]
      if (includeConfidence) {
        const confColor = person.reportsToConfidence === 'high' ? '059669'
          : person.reportsToConfidence === 'medium' ? 'D97706' : 'DC2626'
        row.push({
          text: person.reportsToConfidence,
          options: { fontSize: 9, color: confColor, fill: { color: bgFill }, fontFace: 'Helvetica' },
        })
      }
      rows.push(row)
    })

    const colW = includeConfidence ? [2.2, 3.0, 2.2, 1.5] : [2.8, 3.5, 2.8]

    slide.addTable(rows, {
      x: 0.5, y: 1.5, w: 9,
      colW,
      border: { type: 'solid', pt: 0.5, color: hexToRgb(t.colors.border) },
      rowH: 0.35,
    })

    if (memberPeople.length > 12) {
      slide.addText(`+ ${memberPeople.length - 12} more members`, {
        x: 0.5, y: 4.8, w: 4, h: 0.3,
        fontSize: 9,
        italic: true,
        color: secondaryColor,
        fontFace: 'Helvetica',
      })
    }
  })

  // ────── FINAL SLIDE: METRICS ──────
  const finalSlide = pptx.addSlide()
  finalSlide.background = { color: bgColor }

  finalSlide.addText('Key Metrics', {
    x: 0.5, y: 0.3, w: 9, h: 0.6,
    fontSize: 24,
    bold: true,
    color: textColor,
    fontFace: 'Helvetica',
  })

  // Metrics grid (2x3)
  const metricsData = [
    { label: 'Total People', value: String(org.inferenceStats.totalPeople) },
    { label: 'Departments', value: String(departments.length) },
    { label: 'Completeness Score', value: `${org.completenessScore}%` },
    { label: 'Explicit Relationships', value: String(org.inferenceStats.explicitRelationships) },
    { label: 'Inferred Relationships', value: String(org.inferenceStats.inferredRelationships) },
    { label: 'Orphan Nodes', value: String(org.inferenceStats.orphanNodes) },
  ]

  metricsData.forEach((m, i) => {
    const col = i % 3
    const row = Math.floor(i / 3)
    const x = 0.5 + col * 3.1
    const y = 1.2 + row * 1.5

    finalSlide.addShape(pptx.ShapeType.roundRect, {
      x, y, w: 2.8, h: 1.2,
      fill: { color: surfaceColor },
      rectRadius: 0.1,
      line: { color: hexToRgb(t.colors.border), width: 0.5 },
    })

    finalSlide.addText(m.label, {
      x: x + 0.15, y: y + 0.15, w: 2.5, h: 0.35,
      fontSize: 11,
      color: secondaryColor,
      fontFace: 'Helvetica',
    })

    finalSlide.addText(m.value, {
      x: x + 0.15, y: y + 0.5, w: 2.5, h: 0.5,
      fontSize: 28,
      bold: true,
      color: textColor,
      fontFace: 'Helvetica',
    })
  })

  // Confidence breakdown
  if (includeConfidence) {
    const confCounts = { high: 0, medium: 0, low: 0 }
    people.forEach(p => { confCounts[p.reportsToConfidence]++ })

    finalSlide.addText('Confidence Breakdown', {
      x: 0.5, y: 4.2, w: 4, h: 0.4,
      fontSize: 14,
      bold: true,
      color: textColor,
      fontFace: 'Helvetica',
    })

    const confItems = [
      { label: 'High', count: confCounts.high, color: '059669' },
      { label: 'Medium', count: confCounts.medium, color: 'D97706' },
      { label: 'Low', count: confCounts.low, color: 'DC2626' },
    ]

    confItems.forEach((item, i) => {
      const x = 0.5 + i * 2.5
      finalSlide.addShape(pptx.ShapeType.ellipse, {
        x, y: 4.7, w: 0.15, h: 0.15,
        fill: { color: item.color },
      })
      finalSlide.addText(`${item.label}: ${item.count}`, {
        x: x + 0.25, y: 4.62, w: 2, h: 0.3,
        fontSize: 10,
        color: textColor,
        fontFace: 'Helvetica',
      })
    })
  }

  // Generate blob
  const output = await pptx.write({ outputType: 'blob' }) as Blob
  return output
}
