export { runPipeline, autoDetectColumns } from './pipeline'
export type { PipelineResult, PipelineProgress } from './pipeline'
export { normalizeTitle, classifySeniority, getSeniorityScore, inferDepartmentFromTitle } from './seniority'
export { clusterDepartments } from './department-clustering'
export { buildHierarchy } from './hierarchy'
export { detectGaps } from './gap-detector'
export { calculateConfidence, getConfidenceColor } from './confidence'
export { parseCSV, csvToRecords } from './csv-parser'
export { buildMarketReport } from './report-pipeline'
export type { ReportPipelineProgress } from './report-pipeline'
export { resolveLogoUrl, guessDomain, getLogoUrl, getInitialsPlaceholder } from './logo-fetcher'
