'use client'

import { useEffect, useState, useRef } from 'react'
import { createClient } from '@/lib/supabase/client'

interface BrandingData {
  company_name: string
  phone: string
  email: string
  accent_color: string
  logo_path: string | null
  logo_url: string | null
}

const PRESET_COLORS = [
  '#0D7377', '#1e3a5f', '#2d3748', '#7c3aed',
  '#0369a1', '#b91c1c', '#065f46', '#92400e',
]

export default function BrandingSettingsPage() {
  const [branding, setBranding] = useState<BrandingData>({
    company_name: '', phone: '', email: '',
    accent_color: '#0D7377', logo_path: null, logo_url: null,
  })
  const [saving, setSaving] = useState(false)
  const [saved, setSaved] = useState(false)
  const [uploading, setUploading] = useState(false)
  const fileRef = useRef<HTMLInputElement>(null)

  useEffect(() => {
    fetch('/api/branding').then(r => r.json()).then(setBranding)
  }, [])

  const save = async () => {
    setSaving(true)
    setSaved(false)
    await fetch('/api/branding', {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(branding),
    })
    setSaving(false)
    setSaved(true)
    setTimeout(() => setSaved(false), 2000)
  }

  const uploadLogo = async (file: File) => {
    setUploading(true)
    const supabase = createClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return

    const ext = file.name.split('.').pop() || 'png'
    const path = `${user.id}/logo.${ext}`

    const { error } = await supabase.storage.from('logos').upload(path, file, { upsert: true })
    if (error) {
      console.error('Upload failed:', error)
      setUploading(false)
      return
    }

    // Update branding table with logo path
    await supabase.from('branding').upsert({
      user_id: user.id,
      logo_path: path,
      updated_at: new Date().toISOString(),
    }, { onConflict: 'user_id' })

    // Get signed URL for preview
    const { data: signed } = await supabase.storage.from('logos').createSignedUrl(path, 3600)
    setBranding(prev => ({ ...prev, logo_path: path, logo_url: signed?.signedUrl || null }))
    setUploading(false)
  }

  return (
    <div>
      <h2 className="font-[family-name:var(--font-heading)] text-2xl font-semibold text-[#1A1A1A] mb-1">
        Branding
      </h2>
      <p className="text-sm text-[#6B7280] mb-8">
        Customise how your reports look when exported to PDF.
      </p>

      {/* Live Preview */}
      <div className="mb-8 bg-white border border-[#E2E1DE] rounded-lg overflow-hidden">
        <div className="px-3 py-1.5 border-b border-[#E2E1DE] bg-[#FAFAF8]">
          <span className="text-[10px] text-[#6B7280] uppercase tracking-wider font-medium">PDF Header Preview</span>
        </div>
        <div
          className="px-5 py-4 flex items-center gap-3 transition-colors"
          style={{ backgroundColor: darken(branding.accent_color, 0.3) }}
        >
          {branding.logo_url ? (
            <img src={branding.logo_url} alt="Logo" className="w-8 h-8 object-contain rounded" />
          ) : (
            <div className="w-8 h-8 rounded bg-white/20 flex items-center justify-center">
              <span className="text-white text-[9px] font-bold">
                {(branding.company_name || 'OB').split(/\s+/).map(w => w[0]?.toUpperCase()).join('').slice(0, 2)}
              </span>
            </div>
          )}
          <div>
            <p className="text-white text-sm font-bold">Market Intelligence Report</p>
            <p className="text-white/50 text-[10px]">
              {branding.company_name ? `Prepared by ${branding.company_name}` : 'Generated by CompBrief'}
            </p>
          </div>
        </div>
      </div>

      <div className="space-y-6 max-w-[500px]">
        {/* Logo */}
        <div>
          <label className="block text-xs font-medium text-[#6B7280] uppercase tracking-wide mb-2">
            Logo
          </label>
          <div className="flex items-center gap-4">
            {branding.logo_url ? (
              <img src={branding.logo_url} alt="Logo" className="w-14 h-14 object-contain rounded border border-[#E2E1DE]" />
            ) : (
              <div className="w-14 h-14 rounded border border-dashed border-[#E2E1DE] flex items-center justify-center">
                <span className="text-xs text-[#6B7280]">No logo</span>
              </div>
            )}
            <button
              onClick={() => fileRef.current?.click()}
              disabled={uploading}
              className="text-sm font-medium text-[#0D7377] hover:underline disabled:opacity-50"
            >
              {uploading ? 'Uploading...' : 'Upload logo'}
            </button>
            <input
              ref={fileRef}
              type="file"
              accept="image/*"
              className="hidden"
              onChange={e => {
                const f = e.target.files?.[0]
                if (f) uploadLogo(f)
              }}
            />
          </div>
        </div>

        {/* Accent color */}
        <div>
          <label className="block text-xs font-medium text-[#6B7280] uppercase tracking-wide mb-2">
            Accent colour
          </label>
          <div className="flex items-center gap-2 mb-2">
            {PRESET_COLORS.map(c => (
              <button
                key={c}
                onClick={() => setBranding(prev => ({ ...prev, accent_color: c }))}
                className={`w-7 h-7 rounded-full border-2 transition-transform ${
                  branding.accent_color === c ? 'border-[#1A1A1A] scale-110' : 'border-transparent'
                }`}
                style={{ backgroundColor: c }}
              />
            ))}
          </div>
          <input
            type="text"
            value={branding.accent_color}
            onChange={e => setBranding(prev => ({ ...prev, accent_color: e.target.value }))}
            placeholder="#0D7377"
            className="w-32 text-sm border border-[#E2E1DE] rounded-md px-3 py-1.5 bg-white text-[#1A1A1A] focus:outline-none focus:ring-2 focus:ring-[#0D7377] font-[family-name:var(--font-mono)]"
          />
        </div>

        {/* Company name */}
        <div>
          <label className="block text-xs font-medium text-[#6B7280] uppercase tracking-wide mb-1.5">
            Company name
          </label>
          <input
            type="text"
            value={branding.company_name}
            onChange={e => setBranding(prev => ({ ...prev, company_name: e.target.value }))}
            placeholder="Ashworth Sterling Partners"
            className="w-full text-sm border border-[#E2E1DE] rounded-md px-3 py-2 bg-white text-[#1A1A1A] focus:outline-none focus:ring-2 focus:ring-[#0D7377]"
          />
        </div>

        {/* Phone */}
        <div>
          <label className="block text-xs font-medium text-[#6B7280] uppercase tracking-wide mb-1.5">
            Phone <span className="text-[#6B7280]/50">(optional)</span>
          </label>
          <input
            type="tel"
            value={branding.phone}
            onChange={e => setBranding(prev => ({ ...prev, phone: e.target.value }))}
            placeholder="+44 20 7123 4567"
            className="w-full text-sm border border-[#E2E1DE] rounded-md px-3 py-2 bg-white text-[#1A1A1A] focus:outline-none focus:ring-2 focus:ring-[#0D7377]"
          />
        </div>

        {/* Email */}
        <div>
          <label className="block text-xs font-medium text-[#6B7280] uppercase tracking-wide mb-1.5">
            Email <span className="text-[#6B7280]/50">(optional)</span>
          </label>
          <input
            type="email"
            value={branding.email}
            onChange={e => setBranding(prev => ({ ...prev, email: e.target.value }))}
            placeholder="research@ashworth-sterling.com"
            className="w-full text-sm border border-[#E2E1DE] rounded-md px-3 py-2 bg-white text-[#1A1A1A] focus:outline-none focus:ring-2 focus:ring-[#0D7377]"
          />
        </div>

        {/* Save */}
        <div className="flex items-center gap-3 pt-2">
          <button
            onClick={save}
            disabled={saving}
            className="bg-[#0D7377] text-white text-sm font-medium rounded-md px-6 py-2.5 hover:bg-[#095B5E] transition-colors disabled:opacity-50"
          >
            {saving ? 'Saving...' : 'Save branding'}
          </button>
          {saved && <span className="text-sm text-[#059669]">Saved</span>}
        </div>
      </div>
    </div>
  )
}

function darken(hex: string, amount: number): string {
  const clean = hex.replace('#', '')
  if (clean.length !== 6) return hex
  const r = Math.max(0, Math.round(parseInt(clean.slice(0, 2), 16) * (1 - amount)))
  const g = Math.max(0, Math.round(parseInt(clean.slice(2, 4), 16) * (1 - amount)))
  const b = Math.max(0, Math.round(parseInt(clean.slice(4, 6), 16) * (1 - amount)))
  return `rgb(${r}, ${g}, ${b})`
}
